### ISSUE TITLE
ES for get list of tasks is too slow

### ISSUE THREAD

**Issue by JacHammer** [CMPUT301W18T16/SpaghettiCodeHQ#22]
getListOfTask method under ElasticFactory class downloads every task of the user all at once once it's called, including photos (and GC removes them as they are not used, which take another fair amount of time). It would be a lot faster if it simply gets the task name and bid status (requirment US 01.02.01) from the server.

**Comment by shardul-shah** [comment]
@JacHammer Is this closed now?
